### ISSUE TITLE
too old bundled `pact` `1.38` for token support - `pact-provider-verifier` ignores `--broker-token` option

### ISSUE THREAD

**Issue by pluederitz** [pact-foundation/pact-ruby-standalone#33]
Publishing verification results to pactflow broker does not work using the `pactBrokerToken` because `--broker-token` is ignored and no token header is send to broker in broker HTTPS request.
Thats why pactflow broker server returns always 401.

code analysis result:
- `pact-provider-verifier` uses a too old version of `Pact::Hal::HttpClient` of `pact-ruby`
- `pact-ruby-standalone` release `pact-1.64.1` (and also `pact-1.65.0`) contains a to old version `1.38.0` of `pact-ruby`
- Minimum `1.40.0` of `pact-ruby` is required for token support.

see added token feature => https://github.com/pact-foundation/pact-ruby/blame/master/lib/pact/hal/http_client.rb#L13

here the (outside-analysis) details:

system: macOS 10.14.4

Problems exist on using npm module `@pact-foundation/pact` (version 8.2.4)
and also on `pact-ruby-standalone` (release pact-1.64.1, which is also used by npm module `@pact-foundation/pact-node` 8.3.2 internally).

"package.json":
```
  ...
  "devDependencies": {
    "@pact-foundation/pact": "^8.2.4",
  },
  ...
```

node-js javascript test: (identity/auth values are replaced by XXX)
```
...
output = await new Verifier({
  logLevel: 'debug',
  pactBrokerUrl: 'https://umiXXX.pact.dius.com.au/',
  pactBrokerToken: '1FciXXX',
  publishVerificationResult: true,
  providerVersion: '0.0.1',
  tags: ['local-test'],
  provider: 'FirebaseMobileBackend',
  providerBaseUrl: 'http://127.0.0.1:1237',
  stateHandlers,
}).verifyProvider();
...
```
generates standalone `pact-provider-verifier` execution call (debug log):
(the `--broker-token` option is correctly set)

```
'./standalone/darwin-1.64.1/bin/pact-provider-verifier --provider-states-setup-url 'http://localhost:53267/_pactSetup' --pact-broker-base-url 'https://umiXXX.pact.dius.com.au/' --broker-token '1FciXXX' --publish-verification-results 'true' --provider-app-version '0.0.1' --provider 'FirebaseMobileBackend' --provider-base-url 'http://localhost:53267'
```

which execution results in:
```
Error: XXX/node_modules/@pact-foundation/pact-node/standalone/darwin-1.64.1/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/hal/entity.rb:102:in `assert_success!': Error retrieving https://umiXXX.pact.dius.com.au/ status=401  (Pact::Hal::ErrorResponseReturned)
   from XXX/node_modules/@pact-foundation/pact-node/standalone/darwin-1.64.1/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/pact_broker/fetch_pacts.rb:75:in `index'
   from XXX/node_modules/@pact-foundation/pact-node/standalone/darwin-1.64.1/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/pact_broker/fetch_pacts.rb:38:in `call'
   from XXX/node_modules/@pact-foundation/pact-node/standalone/darwin-1.64.1/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/pact_broker/fetch_pacts.rb:33:in `call'
   from XXX/node_modules/@pact-foundation/pact-node/standalone/darwin-1.64.1/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/pact_broker.rb:12:in `fetch_pact_uris'
   from XXX/node_modules/@pact-foundation/pact-node/standalone/darwin-1.64.1/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/aggregate_pact_configs.rb:38:in `non_pending_pact_uris'
   from XXX/node_modules/@pact-foundation/pact-node/standalone/darwin-1.64.1/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/aggregate_pact_configs.rb:31:in `pacts_urls_from_broker'
```

Adding the verbose option `-v` and run directly from command line results:
(here you can see the missing `Authorization: Bearer [token]` HTTP header)

```
INFO: Fetching pacts for FirebaseMobileBackend from https://umiXXX.pact.dius.com.au/
opening connection to umiXXX.pact.dius.com.au:443...
opened
starting SSL for umiXXX.pact.dius.com.au:443...
SSL established
<- "GET /? HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: application/hal+json\r\nUser-Agent: Ruby\r\nHost: umiXXX.pact.dius.com.au\r\n\r\n"
-> "HTTP/1.1 401 Unauthorized\r\n"
-> "Date: Mon, 20 May 2019 11:15:47 GMT\r\n"
-> "Content-Type: text/plain\r\n"
-> "Content-Length: 0\r\n"
-> "Connection: keep-alive\r\n"
-> "Status: 401 Unauthorized\r\n"
-> "X-Saas-Broker-Git-Sha: 693638fe3e3c6cb7aaa8ef34b2f9a81bb8ea2036\r\n"
-> "X-Pact-Broker-Git-Sha: 742d506c8cd63cc4c7e25aecfb0e31ab2af3a7e5\r\n"
-> "WWW-Authenticate: Basic realm=\"Restricted area\"\r\n"
-> "X-Pact-Broker-Version: 2.31.0\r\n"
-> "X-Request-Id: 03f5e33bc78c267819fb4687df518a85\r\n"
-> "X-Frame-Options: SAMEORIGIN\r\n"
-> "X-XSS-Protection: 1; mode=block\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Referrer-Policy: strict-origin\r\n"
-> "Strict-Transport-Security: max-age=31536000 ; includeSubDomains\r\n"
-> "\r\n"
reading 0 bytes...
-> ""
read 0 bytes
Conn keep-alive
XXX/node_modules/@pact-foundation/pact-node/standalone/darwin-1.64.1/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/hal/entity.rb:102:in `assert_success!': Error retrieving https://umiXXX.pact.dius.com.au/ status=401  (Pact::Hal::ErrorResponseReturned)
```

But our token works perfectly on standalone tool to publish pact files:

`pact-broker publish` execution with same broker URL and token - an authorization header is sent:
```
./pact-standalone/pact/bin/pact-broker publish "$PACT_DIR" \
  "--broker-base-url=$BROKER" \
  "--broker-token=$BROKER_TOKEN" \
  "--consumer-app-version=$VERSION" \
  "--tag=$TAG" -v
```

```
Tagging version 0.2-1-d31385613e520b8f27b3ead612248ad442ca2738 of IosConsumerApp as "local-test"
opening connection to umiXXX.pact.dius.com.au:443...
opened
starting SSL for umiXXX.pact.dius.com.au:443...
SSL established
<- "PUT /pacticipants/IosConsumerApp/versions/0.2-1-d31385613e520b8f27b3ead612248ad442ca2738/tags/local-test HTTP/1.1\r\nAuthorization: Bearer 1FciXXX\r\nAccept: application/hal+json, application/json\r\nContent-Type: application/json\r\nContent-Length: 0\r\nConnection: close\r\nHost: umiXXX.pact.dius.com.au\r\n\r\n"
<- ""
-> "HTTP/1.1 200 OK\r\n"
-> "Date: Mon, 20 May 2019 09:49:04 GMT\r\n"
-> "Content-Type: application/hal+json;charset=utf-8\r\n"
-> "Content-Length: 689\r\n"
-> "Connection: close\r\n"
-> "Status: 200 OK\r\n"
-> "X-Saas-Broker-Git-Sha: 693638fe3e3c6cb7aaa8ef34b2f9a81bb8ea2036\r\n"
-> "X-Pact-Broker-Git-Sha: 742d506c8cd63cc4c7e25aecfb0e31ab2af3a7e5\r\n"
-> "X-Pact-Broker-Version: 2.31.0\r\n"
-> "X-Request-Id: 12bd12ebbd57a669c84097b305f84a0e\r\n"
-> "X-Frame-Options: SAMEORIGIN\r\n"
-> "X-XSS-Protection: 1; mode=block\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Referrer-Policy: strict-origin\r\n"
-> "Strict-Transport-Security: max-age=31536000 ; includeSubDomains\r\n"
-> "\r\n"
reading 689 bytes...
```

(Doing authentication via username/password does not work with our pactflow account generally. Only using token works - and only on pact file publishing, not on verification)

**Comment by mefellows** [comment]
I've just reproduced this issue also.

**Comment by mefellows** [comment]
Looks like there might be a compatibility issue. Will investigate.

![Screen Shot 2019-05-22 at 12 24 15 pm](https://user-images.githubusercontent.com/53900/58143007-947d0e00-7c8c-11e9-92aa-28cc798dfc92.png)

**Comment by bethesque** [comment]
I'll have a look.

**Comment by mefellows** [comment]
oky doky, thanks

**Comment by bethesque** [comment]
Ok, please upgrade to `1.65.1`.

**Comment by mefellows** [comment]
Thanks @pluederitz, I've updated the version in `pact-node` and a release going out shortly. It's a micro version change, so an update should pull straight through (`pact` allows minor backwards-compatible revision updates).
