### ISSUE TITLE
Error when reading path matchers in v3 pact

### ISSUE THREAD

**Issue by microhod** [pact-foundation/pact-ruby-standalone#44]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Upgraded to the latest version of the relevant libraries
* [x] Checked to see if the issue has already been raised
* [x] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions

* **pact library:** pactNET 2.5.0, pact-ruby-standalone 1.78.0
* **pact-ruby-standalone:** 1.78.0
* **OS**: Windows 10 1809, Ubuntu 18.04.2

## Expected behaviour

pact-ruby-standalone parses the v3 pact but ignores v3 matchers when running verification (as shown on the feature support page https://docs.pact.io/feature_support).

## Actual behaviour

pact-ruby-standalone fails to parse the v3 pact when it has path matchers.

## Steps to reproduce

Gist: https://gist.github.com/microhod/cc3cc88c90d5a0f1d13df0cb3b1743f4

## Relevent log files
```
INFO: Reading pact at client-server.json
/home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/matching_rules/v3/merge.rb:110:in `[]': no implicit conversion of String into Integer (TypeError)
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/matching_rules/v3/merge.rb:110:in `block in log_ignored_rules'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/matching_rules/v3/merge.rb:109:in `each'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/matching_rules/v3/merge.rb:109:in `log_ignored_rules'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/matching_rules/v3/merge.rb:21:in `block in call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/matching_rules/v3/merge.rb:21:in `tap'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/matching_rules/v3/merge.rb:21:in `call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/matching_rules/v3/merge.rb:10:in `call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/matching_rules.rb:26:in `merge'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/interaction_v3_parser.rb:50:in `block in parse_request_with_non_string_body'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/interaction_v3_parser.rb:49:in `each'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/interaction_v3_parser.rb:49:in `each_with_object'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/interaction_v3_parser.rb:49:in `parse_request_with_non_string_body'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/interaction_v3_parser.rb:35:in `parse_request'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/interaction_v3_parser.rb:15:in `call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/interaction_parser.rb:20:in `parse_v3_interaction'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/interaction_parser.rb:11:in `call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/interaction.rb:22:in `from_hash'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/http_consumer_contract_parser.rb:16:in `block in call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/http_consumer_contract_parser.rb:16:in `each'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/http_consumer_contract_parser.rb:16:in `each_with_index'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/http_consumer_contract_parser.rb:16:in `each'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/http_consumer_contract_parser.rb:16:in `collect'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/http_consumer_contract_parser.rb:16:in `call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/consumer_contract.rb:45:in `block in from_hash'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/consumer_contract.rb:44:in `each'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/consumer_contract.rb:44:in `from_hash'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.13.0/lib/pact/consumer_contract/consumer_contract.rb:52:in `from_json'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-1.47.0/lib/pact/provider/rspec.rb:34:in `honour_pactfile'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-1.47.0/lib/pact/provider/pact_spec_runner.rb:125:in `block in initialize_specs'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-1.47.0/lib/pact/provider/pact_spec_runner.rb:119:in `each'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-1.47.0/lib/pact/provider/pact_spec_runner.rb:119:in `initialize_specs'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-1.47.0/lib/pact/provider/pact_spec_runner.rb:33:in `run'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-1.47.0/lib/pact/cli/run_pact_verification.rb:67:in `run_with_pact_uri_object'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-1.47.0/lib/pact/cli/run_pact_verification.rb:50:in `run_specs'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-1.47.0/lib/pact/cli/run_pact_verification.rb:21:in `call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-1.47.0/lib/pact/cli/run_pact_verification.rb:13:in `call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.28.0/lib/pact/provider_verifier/app.rb:172:in `verify_pact'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.28.0/lib/pact/provider_verifier/app.rb:43:in `block in call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.28.0/lib/pact/provider_verifier/app.rb:42:in `collect'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.28.0/lib/pact/provider_verifier/app.rb:42:in `call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.28.0/lib/pact/provider_verifier/app.rb:34:in `call'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.28.0/lib/pact/provider_verifier/cli/verify.rb:54:in `verify'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /home/samuelho/test/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.28.0/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
        from /home/samuelho/test/pact/lib/app/pact-provider-verifier.rb:33:in `<main>'
```

**Comment by bethesque** [comment]
Thanks. I'll have a look on Thursday as it's my OSS code day.

**Comment by bethesque** [comment]
Sorry, I didn't get to this last Thursday but hope to on the 27th.
